"""borndate

Revision ID: 8fa3267662e7
Revises: f24e1c1a9199
Create Date: 2024-02-11 14:19:33.295513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa3267662e7'
down_revision: Union[str, None] = 'f24e1c1a9199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('born_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'born_date')
    # ### end Alembic commands ###
